### ISSUE TITLE
Question: CoinMarketCap Halting Public API

### ISSUE THREAD

**Issue by irishpride44** [CodeSolz/WooCommerce-AltCoin-Payment-Gateway#1]
CoinMarketCap is halting their Public API and requiring a API Key to use their calculations (later this year).

https://coinmarketcap.com/api/

"The Public API will be migrating to the new, more powerful Professional API on December 4th, 2018. Please update your application to use the free tier of the Professional API before then. "

CoinGecko is continuing to allow their free public API to be used btw.

**Comment by tuhin18003** [comment]
Thanks for your information. I will update it as soon as possible before their migration.
